name: cimax_films_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  gap: ^3.0.1
  provider: ^6.1.2
  carousel_slider: ^4.2.1
  intl: ^0.19.0
  connectivity_plus: ^6.0.3
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  sliding_clipped_nav_bar: ^3.1.1
  firebase_core: ^2.31.1
  cloud_firestore: ^4.17.4
  firebase_auth: ^4.19.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/































